# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
